// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.10.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace cdc.customer_risk_assessment.crm.dbo.Users
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class Value : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"Value\",\"namespace\":\"cdc.customer_risk_assessment.crm.dbo" +
				".Users\",\"fields\":[{\"name\":\"UserID\",\"type\":\"int\"},{\"name\":\"PersonID\",\"type\":\"int\"" +
				"}],\"connect.name\":\"cdc.customer_risk_assessment.crm.dbo.Users.Value\"}");
		private int _UserID;
		private int _PersonID;
		public virtual Schema Schema
		{
			get
			{
				return Value._SCHEMA;
			}
		}
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				this._UserID = value;
			}
		}
		public int PersonID
		{
			get
			{
				return this._PersonID;
			}
			set
			{
				this._PersonID = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.UserID;
			case 1: return this.PersonID;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.UserID = (System.Int32)fieldValue; break;
			case 1: this.PersonID = (System.Int32)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
