// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.10.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace cdc.customer_risk_assessment.crm.dbo.InternationalAddress
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class Value : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""Value"",""namespace"":""cdc.customer_risk_assessment.crm.dbo.InternationalAddress"",""fields"":[{""name"":""InternationalAddressID"",""type"":""int""},{""name"":""CountryID"",""type"":""int""}],""connect.name"":""cdc.customer_risk_assessment.crm.dbo.InternationalAddress.Value""}");
		private int _InternationalAddressID;
		private int _CountryID;
		public virtual Schema Schema
		{
			get
			{
				return Value._SCHEMA;
			}
		}
		public int InternationalAddressID
		{
			get
			{
				return this._InternationalAddressID;
			}
			set
			{
				this._InternationalAddressID = value;
			}
		}
		public int CountryID
		{
			get
			{
				return this._CountryID;
			}
			set
			{
				this._CountryID = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.InternationalAddressID;
			case 1: return this.CountryID;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.InternationalAddressID = (System.Int32)fieldValue; break;
			case 1: this.CountryID = (System.Int32)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
