version: '3.7'

services:
  cra-factors-listener:
    entrypoint: ""
    image: cra-factors-listener
    container_name: cra-factors-listener
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      START_WITHOUT_ENVOY: "true"
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://*:8080"