// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.10.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace cdc.customer_risk_assessment.crm.dbo.PoliticallyExposedPerson
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class Key : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"Key\",\"namespace\":\"cdc.customer_risk_assessment.crm.dbo.P" +
				"oliticallyExposedPerson\",\"fields\":[{\"name\":\"PoliticallyExposedPersonID\",\"type\":\"" +
				"int\"}],\"connect.name\":\"cdc.customer_risk_assessment.crm.dbo.PoliticallyExposedPe" +
				"rson.Key\"}");
		private int _PoliticallyExposedPersonID;
		public virtual Schema Schema
		{
			get
			{
				return Key._SCHEMA;
			}
		}
		public int PoliticallyExposedPersonID
		{
			get
			{
				return this._PoliticallyExposedPersonID;
			}
			set
			{
				this._PoliticallyExposedPersonID = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.PoliticallyExposedPersonID;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.PoliticallyExposedPersonID = (System.Int32)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
