// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.10.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace cdc.customer_risk_assessment.crm.dbo.PoliticallyExposedPerson
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class Value : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""Value"",""namespace"":""cdc.customer_risk_assessment.crm.dbo.PoliticallyExposedPerson"",""fields"":[{""name"":""PoliticallyExposedPersonID"",""type"":""int""},{""name"":""PersonID"",""type"":""int""},{""name"":""PEP_IsPoliticallyExposed"",""type"":""int""}],""connect.name"":""cdc.customer_risk_assessment.crm.dbo.PoliticallyExposedPerson.Value""}");
		private int _PoliticallyExposedPersonID;
		private int _PersonID;
		private int _PEP_IsPoliticallyExposed;
		public virtual Schema Schema
		{
			get
			{
				return Value._SCHEMA;
			}
		}
		public int PoliticallyExposedPersonID
		{
			get
			{
				return this._PoliticallyExposedPersonID;
			}
			set
			{
				this._PoliticallyExposedPersonID = value;
			}
		}
		public int PersonID
		{
			get
			{
				return this._PersonID;
			}
			set
			{
				this._PersonID = value;
			}
		}
		public int PEP_IsPoliticallyExposed
		{
			get
			{
				return this._PEP_IsPoliticallyExposed;
			}
			set
			{
				this._PEP_IsPoliticallyExposed = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.PoliticallyExposedPersonID;
			case 1: return this.PersonID;
			case 2: return this.PEP_IsPoliticallyExposed;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.PoliticallyExposedPersonID = (System.Int32)fieldValue; break;
			case 1: this.PersonID = (System.Int32)fieldValue; break;
			case 2: this.PEP_IsPoliticallyExposed = (System.Int32)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
