// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.10.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace cdc.customer_risk_assessment.crm.dbo.PersonEmployment
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class Key : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"Key\",\"namespace\":\"cdc.customer_risk_assessment.crm.dbo.P" +
				"ersonEmployment\",\"fields\":[{\"name\":\"PersonEmploymentID\",\"type\":\"int\"}],\"connect." +
				"name\":\"cdc.customer_risk_assessment.crm.dbo.PersonEmployment.Key\"}");
		private int _PersonEmploymentID;
		public virtual Schema Schema
		{
			get
			{
				return Key._SCHEMA;
			}
		}
		public int PersonEmploymentID
		{
			get
			{
				return this._PersonEmploymentID;
			}
			set
			{
				this._PersonEmploymentID = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.PersonEmploymentID;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.PersonEmploymentID = (System.Int32)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
