// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.10.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace cdc.customer_risk_assessment.crm.dbo.PersonEmployment
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class Value : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""Value"",""namespace"":""cdc.customer_risk_assessment.crm.dbo.PersonEmployment"",""fields"":[{""name"":""PersonEmploymentID"",""type"":""int""},{""name"":""PersonID"",""type"":""int""},{""name"":""PE_JobTitle"",""default"":null,""type"":[""null"",""string""]},{""name"":""PE_IsJobTitleVerified"",""default"":false,""type"":""boolean""},{""name"":""EmploymentTypeID"",""type"":""int""}],""connect.name"":""cdc.customer_risk_assessment.crm.dbo.PersonEmployment.Value""}");
		private int _PersonEmploymentID;
		private int _PersonID;
		private string _PE_JobTitle;
		private bool _PE_IsJobTitleVerified;
		private int _EmploymentTypeID;
		public virtual Schema Schema
		{
			get
			{
				return Value._SCHEMA;
			}
		}
		public int PersonEmploymentID
		{
			get
			{
				return this._PersonEmploymentID;
			}
			set
			{
				this._PersonEmploymentID = value;
			}
		}
		public int PersonID
		{
			get
			{
				return this._PersonID;
			}
			set
			{
				this._PersonID = value;
			}
		}
		public string PE_JobTitle
		{
			get
			{
				return this._PE_JobTitle;
			}
			set
			{
				this._PE_JobTitle = value;
			}
		}
		public bool PE_IsJobTitleVerified
		{
			get
			{
				return this._PE_IsJobTitleVerified;
			}
			set
			{
				this._PE_IsJobTitleVerified = value;
			}
		}
		public int EmploymentTypeID
		{
			get
			{
				return this._EmploymentTypeID;
			}
			set
			{
				this._EmploymentTypeID = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.PersonEmploymentID;
			case 1: return this.PersonID;
			case 2: return this.PE_JobTitle;
			case 3: return this.PE_IsJobTitleVerified;
			case 4: return this.EmploymentTypeID;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.PersonEmploymentID = (System.Int32)fieldValue; break;
			case 1: this.PersonID = (System.Int32)fieldValue; break;
			case 2: this.PE_JobTitle = (System.String)fieldValue; break;
			case 3: this.PE_IsJobTitleVerified = (System.Boolean)fieldValue; break;
			case 4: this.EmploymentTypeID = (System.Int32)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
