// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.10.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace cdc.customer_risk_assessment.crm.dbo.Persons
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class Value : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"Value\",\"namespace\":\"cdc.customer_risk_assessment.crm.dbo" +
				".Persons\",\"fields\":[{\"name\":\"PersonID\",\"type\":\"int\"},{\"name\":\"CustomerUUID\",\"typ" +
				"e\":\"string\"}],\"connect.name\":\"cdc.customer_risk_assessment.crm.dbo.Persons.Value" +
				"\"}");
		private int _PersonID;
		private string _CustomerUUID;
		public virtual Schema Schema
		{
			get
			{
				return Value._SCHEMA;
			}
		}
		public int PersonID
		{
			get
			{
				return this._PersonID;
			}
			set
			{
				this._PersonID = value;
			}
		}
		public string CustomerUUID
		{
			get
			{
				return this._CustomerUUID;
			}
			set
			{
				this._CustomerUUID = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.PersonID;
			case 1: return this.CustomerUUID;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.PersonID = (System.Int32)fieldValue; break;
			case 1: this.CustomerUUID = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
