// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.10.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace cdc.customer_risk_assessment.crm.dbo.PersonAddress
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class Value : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""Value"",""namespace"":""cdc.customer_risk_assessment.crm.dbo.PersonAddress"",""fields"":[{""name"":""PersonAddressID"",""type"":""int""},{""name"":""AddressID"",""type"":""int""},{""name"":""AddressTypeID"",""type"":""int""},{""name"":""PersonID"",""type"":""int""}],""connect.name"":""cdc.customer_risk_assessment.crm.dbo.PersonAddress.Value""}");
		private int _PersonAddressID;
		private int _AddressID;
		private int _AddressTypeID;
		private int _PersonID;
		public virtual Schema Schema
		{
			get
			{
				return Value._SCHEMA;
			}
		}
		public int PersonAddressID
		{
			get
			{
				return this._PersonAddressID;
			}
			set
			{
				this._PersonAddressID = value;
			}
		}
		public int AddressID
		{
			get
			{
				return this._AddressID;
			}
			set
			{
				this._AddressID = value;
			}
		}
		public int AddressTypeID
		{
			get
			{
				return this._AddressTypeID;
			}
			set
			{
				this._AddressTypeID = value;
			}
		}
		public int PersonID
		{
			get
			{
				return this._PersonID;
			}
			set
			{
				this._PersonID = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.PersonAddressID;
			case 1: return this.AddressID;
			case 2: return this.AddressTypeID;
			case 3: return this.PersonID;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.PersonAddressID = (System.Int32)fieldValue; break;
			case 1: this.AddressID = (System.Int32)fieldValue; break;
			case 2: this.AddressTypeID = (System.Int32)fieldValue; break;
			case 3: this.PersonID = (System.Int32)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
