// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.10.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace cdc.customer_risk_assessment.crm.dbo.Account
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class Envelope : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"Envelope\",\"namespace\":\"cdc.customer_risk_assessment.crm." +
				"dbo.Account\",\"fields\":[{\"name\":\"before\",\"default\":null,\"type\":[\"null\",{\"type\":\"r" +
				"ecord\",\"name\":\"Value\",\"namespace\":\"cdc.customer_risk_assessment.crm.dbo.Account\"" +
				",\"fields\":[{\"name\":\"AccountID\",\"type\":\"int\"},{\"name\":\"AccountStatusID\",\"default\"" +
				":null,\"type\":[\"null\",\"int\"]}],\"connect.name\":\"cdc.customer_risk_assessment.crm.d" +
				"bo.Account.Value\"}]},{\"name\":\"after\",\"default\":null,\"type\":[\"null\",\"Value\"]},{\"n" +
				"ame\":\"source\",\"type\":{\"type\":\"record\",\"name\":\"Source\",\"namespace\":\"io.debezium.c" +
				"onnector.sqlserver\",\"fields\":[{\"name\":\"version\",\"type\":\"string\"},{\"name\":\"connec" +
				"tor\",\"type\":\"string\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"ts_ms\",\"type\":\"lo" +
				"ng\"},{\"name\":\"snapshot\",\"default\":\"false\",\"type\":[\"string\",\"null\"]},{\"name\":\"db\"" +
				",\"type\":\"string\"},{\"name\":\"schema\",\"type\":\"string\"},{\"name\":\"table\",\"type\":\"stri" +
				"ng\"},{\"name\":\"change_lsn\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"comm" +
				"it_lsn\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"event_serial_no\",\"defa" +
				"ult\":null,\"type\":[\"null\",\"long\"]}],\"connect.name\":\"io.debezium.connector.sqlserv" +
				"er.Source\"}},{\"name\":\"op\",\"type\":\"string\"},{\"name\":\"ts_ms\",\"default\":null,\"type\"" +
				":[\"null\",\"long\"]},{\"name\":\"transaction\",\"default\":null,\"type\":[\"null\",{\"type\":\"r" +
				"ecord\",\"name\":\"ConnectDefault\",\"namespace\":\"io.confluent.connect.avro\",\"fields\":" +
				"[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"total_order\",\"type\":\"long\"},{\"name\":\"dat" +
				"a_collection_order\",\"type\":\"long\"}]}]}],\"connect.name\":\"cdc.customer_risk_assess" +
				"ment.crm.dbo.Account.Envelope\"}");
		private cdc.customer_risk_assessment.crm.dbo.Account.Value _before;
		private cdc.customer_risk_assessment.crm.dbo.Account.Value _after;
		private io.debezium.connector.sqlserver.Source _source;
		private string _op;
		private System.Nullable<System.Int64> _ts_ms;
		private io.confluent.connect.avro.ConnectDefault _transaction;
		public virtual Schema Schema
		{
			get
			{
				return Envelope._SCHEMA;
			}
		}
		public cdc.customer_risk_assessment.crm.dbo.Account.Value before
		{
			get
			{
				return this._before;
			}
			set
			{
				this._before = value;
			}
		}
		public cdc.customer_risk_assessment.crm.dbo.Account.Value after
		{
			get
			{
				return this._after;
			}
			set
			{
				this._after = value;
			}
		}
		public io.debezium.connector.sqlserver.Source source
		{
			get
			{
				return this._source;
			}
			set
			{
				this._source = value;
			}
		}
		public string op
		{
			get
			{
				return this._op;
			}
			set
			{
				this._op = value;
			}
		}
		public System.Nullable<System.Int64> ts_ms
		{
			get
			{
				return this._ts_ms;
			}
			set
			{
				this._ts_ms = value;
			}
		}
		public io.confluent.connect.avro.ConnectDefault transaction
		{
			get
			{
				return this._transaction;
			}
			set
			{
				this._transaction = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.before;
			case 1: return this.after;
			case 2: return this.source;
			case 3: return this.op;
			case 4: return this.ts_ms;
			case 5: return this.transaction;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.before = (cdc.customer_risk_assessment.crm.dbo.Account.Value)fieldValue; break;
			case 1: this.after = (cdc.customer_risk_assessment.crm.dbo.Account.Value)fieldValue; break;
			case 2: this.source = (io.debezium.connector.sqlserver.Source)fieldValue; break;
			case 3: this.op = (System.String)fieldValue; break;
			case 4: this.ts_ms = (System.Nullable<System.Int64>)fieldValue; break;
			case 5: this.transaction = (io.confluent.connect.avro.ConnectDefault)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
