// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.10.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace cdc.customer_risk_assessment.crm.dbo.Account
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class Value : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""Value"",""namespace"":""cdc.customer_risk_assessment.crm.dbo.Account"",""fields"":[{""name"":""AccountID"",""type"":""int""},{""name"":""AccountStatusID"",""default"":null,""type"":[""null"",""int""]}],""connect.name"":""cdc.customer_risk_assessment.crm.dbo.Account.Value""}");
		private int _AccountID;
		private System.Nullable<System.Int32> _AccountStatusID;
		public virtual Schema Schema
		{
			get
			{
				return Value._SCHEMA;
			}
		}
		public int AccountID
		{
			get
			{
				return this._AccountID;
			}
			set
			{
				this._AccountID = value;
			}
		}
		public System.Nullable<System.Int32> AccountStatusID
		{
			get
			{
				return this._AccountStatusID;
			}
			set
			{
				this._AccountStatusID = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.AccountID;
			case 1: return this.AccountStatusID;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.AccountID = (System.Int32)fieldValue; break;
			case 1: this.AccountStatusID = (System.Nullable<System.Int32>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
