// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.10.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace cdc.customer_risk_assessment.crm.dbo.DomesticAddress
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class Value : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"Value\",\"namespace\":\"cdc.customer_risk_assessment.crm.dbo" +
				".DomesticAddress\",\"fields\":[{\"name\":\"DomesticAddressID\",\"type\":\"int\"}],\"connect." +
				"name\":\"cdc.customer_risk_assessment.crm.dbo.DomesticAddress.Value\"}");
		private int _DomesticAddressID;
		public virtual Schema Schema
		{
			get
			{
				return Value._SCHEMA;
			}
		}
		public int DomesticAddressID
		{
			get
			{
				return this._DomesticAddressID;
			}
			set
			{
				this._DomesticAddressID = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.DomesticAddressID;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.DomesticAddressID = (System.Int32)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
